# services:
#   backend:
#     build: .
#     ports:
#       - '8080:8080'
#     environment:
#       - 'DATASOURCE_URL=jdbc:oracle:thin:@//192.168.1.81:1521/free'
#       - 'DATASOURCE_USERNAME=c##teqdev'
#       - 'DATASOURCE_PASSWORD=dev'
#       - 'FRONT_ALLOWED_URL=http://localhost:4200'