export const REQUIRED = 'champ obligatoire';
export const currency_list = [
    { name: 'MRU', code: 'MRU' },
    { name: 'Euro', code: 'EUR' },
    { name: 'Dollar US', code: 'USD' },
    { name: 'Livre sterling', code: 'GBP' },
    { name: 'Franc suisse', code: 'CHF' },
    { name: 'Dollar canadien', code: 'CAD' },
    { name: 'Couronne suédoise', code: 'SEK' },
    { name: 'Couronne norvégienne', code: 'NOK' },
    { name: 'Couronne danoise', code: 'DKK' },
    { name: 'Franc CFA BCEAO', code: 'XOF' },
    { name: 'Yen japonais', code: 'JPY' },
    { name: 'Riyal saoudien', code: 'SAR' },
    { name: 'Dinar koweitien', code: 'KWD' },
    { name: 'Yuan renminbi chinois', code: 'CNY' },
    { name: 'Dirham des Emirats Arabes Unis', code: 'AED' },
    { name: 'Droits de Tirages Spéciaux (DTS)', code: 'XDR' },
    { name: 'Dirham marocain', code: 'MAD' },
    { name: 'Dinar tunisien', code: 'TND' },
    { name: 'Dinar algérien', code: 'DZD' },
    { name: 'Dinar libyen', code: 'LYD' },

];
export const countries = [
    { code: 'AF', name: 'Afghanistan' },
    { code: 'ZA', name: 'Afrique du Sud' },
    { code: 'AL', name: 'Albanie' },
    { code: 'DZ', name: 'Algérie' },
    { code: 'DE', name: 'Allemagne' },
    { code: 'AD', name: 'Andorre' },
    { code: 'AO', name: 'Angola' },
    { code: 'AI', name: 'Anguilla' },
    { code: 'AQ', name: 'Antarctique' },
    { code: 'AG', name: 'Antigua et Barbuda' },
    { code: 'AN', name: 'Antilles Néerlandaises' },
    { code: 'SA', name: 'Arabie Saoudite' },
    { code: 'AR', name: 'Argentine' },
    { code: 'AM', name: 'Arménie' },
    { code: 'AW', name: 'Aruba' },
    { code: 'AU', name: 'Australie' },
    { code: 'AT', name: 'Autriche' },
    { code: 'AZ', name: 'Azerbaijan' },
    { code: 'BS', name: 'Bahamas' },
    { code: 'BH', name: 'Bahreïn' },
    { code: 'BD', name: 'Bangladesh' },
    { code: 'BB', name: 'Barbade' },
    { code: 'BY', name: 'Bélarus' },
    { code: 'BE', name: 'Belgique' },
    { code: 'BZ', name: 'Belize' },
    { code: 'BJ', name: 'Bénin' },
    { code: 'BM', name: 'Bermudes' },
    { code: 'BT', name: 'Bhoutan' },
    { code: 'BO', name: 'Bolivie' },
    { code: 'BA', name: 'Bosnie Herzégovine' },
    { code: 'BW', name: 'Botswana' },
    { code: 'BV', name: 'Bouvet, Œle' },
    { code: 'BR', name: 'Bresil' },
    { code: 'BN', name: 'Brunei Darussalam' },
    { code: 'BG', name: 'Bulgarie' },
    { code: 'BF', name: 'Burkina Faso' },
    { code: 'BI', name: 'Burundi' },
    { code: 'BL', name: 'Burundi local' },
    { code: 'KY', name: 'Caïmans, Œles' },
    { code: 'KH', name: 'Cambodge' },
    { code: 'CM', name: 'Cameroun' },
    { code: 'CA', name: 'Canada' },
    { code: 'CV', name: 'Cap-Vert' },
    { code: 'CF', name: 'Centrafricaine, République' },
    { code: 'CL', name: 'Chili' },
    { code: 'CN', name: 'Chine' },
    { code: 'CX', name: 'Christmas, Œle (Australie)' },
    { code: 'CY', name: 'Chypre' },
    { code: 'code:', name: 'Cocos (Keeling), Œles' },
    { code: 'CO', name: 'Colombie' },
    { code: 'KM', name: 'Comores' },
    { code: 'CG', name: 'Congo (Brazzaville)' },
    { code: 'CD', name: 'Congo, République Démocratique' },
    { code: 'CK', name: 'Cook, Œles' },
    { code: 'KP', name: 'Corée, Rép. Populaire Démocratique' },
    { code: 'KR', name: 'Corée, République de' },
    { code: 'CR', name: 'Costa Rica' },
    { code: 'CI', name: "Côte d'Ivoire" },
    { code: 'HR', name: 'Croatie' },
    { code: 'CU', name: 'Cuba' },
    { code: 'DK', name: 'Danemark' },
    { code: 'DJ', name: 'Djibouti' },
    { code: 'DO', name: 'Dominicaine, République' },
    { code: 'DM', name: 'Dominique' },
    { code: 'EG', name: 'Egypte' },
    { code: 'SV', name: 'El Salvador' },
    { code: 'AE', name: 'Emirats Arabes Unis' },
    { code: 'EC', name: 'Equateur' },
    { code: 'ER', name: 'Erythrée' },
    { code: 'ES', name: 'Espagne' },
    { code: 'EE', name: 'Estonie' },
    { code: 'US', name: 'Etats-Unis' },
    { code: 'ET', name: 'Ethiopie' },
    { code: 'FK', name: 'Falkland, Œles (Malvinas)' },
    { code: 'FO', name: 'Féroé, Œles' },
    { code: 'FJ', name: 'Fiji' },
    { code: 'FI', name: 'Finlande' },
    { code: 'FR', name: 'France' },
    { code: 'GA', name: 'Gabon' },
    { code: 'GM', name: 'Gambie' },
    { code: 'GE', name: 'Géorgie' },
    { code: 'GS', name: 'Géorgie du Sud et Œles sandwich sud' },
    { code: 'GH', name: 'Ghana' },
    { code: 'GI', name: 'Gibraltar' },
    { code: 'GR', name: 'Grèce' },
    { code: 'GD', name: 'Grenade' },
    { code: 'GL', name: 'Groenland' },
    { code: 'GP', name: 'Guadeloupe' },
    { code: 'GU', name: 'Guam' },
    { code: 'GT', name: 'Guatemala' },
    { code: 'GN', name: 'Guinée' },
    { code: 'GQ', name: 'Guinée Equatoriale' },
    { code: 'GW', name: 'Guinée-Bissau' },
    { code: 'GY', name: 'Guyane' },
    { code: 'GF', name: 'Guyane Française' },
    { code: 'HT', name: 'Haïti' },
    { code: 'HM', name: 'Heard et McDonald, Œles' },
    { code: 'HN', name: 'Honduras' },
    { code: 'HK', name: 'Hong-Kong' },
    { code: 'HU', name: 'Hongrie' },
    { code: 'VG', name: 'Iles Vierges Britanniques' },
    { code: 'VI', name: 'Iles Vierges des Etats-Unis' },
    { code: 'IN', name: 'Inde' },
    { code: 'ID', name: 'Indonésie' },
    { code: 'IQ', name: 'Irak' },
    { code: 'IR', name: "Iran, République Islqmique d'" },
    { code: 'IE', name: 'Irlande' },
    { code: 'IS', name: 'Islande' },
    { code: 'IL', name: 'Israël' },
    { code: 'IT', name: 'Italie' },
    { code: 'JM', name: 'Jamaïque' },
    { code: 'JP', name: 'Japon' },
    { code: 'JO', name: 'Jordanie' },
    { code: 'KZ', name: 'Kazakstan' },
    { code: 'KE', name: 'Kenya' },
    { code: 'KG', name: 'Kirghizistan' },
    { code: 'KI', name: 'Kiribati' },
    { code: 'KW', name: 'Koweit' },
    { code: 'LA', name: 'Lao, Rép. Démocratique Populaire' },
    { code: 'LS', name: 'Lesotho' },
    { code: 'LV', name: 'Lettonie' },
    { code: 'LB', name: 'Liban' },
    { code: 'LR', name: 'Libéria' },
    { code: 'LY', name: 'Libyenne, Jamahiriya Arabe' },
    { code: 'LI', name: 'Liechtenstein' },
    { code: 'LT', name: 'Lituanie' },
    { code: 'LU', name: 'Luxembourg' },
    { code: 'MO', name: 'Macao' },
    { code: 'MK', name: 'Macédoine, Ex-république Yougoslave' },
    { code: 'MG', name: 'Madagascar' },
    { code: 'MY', name: 'Malaisie' },
    { code: 'MW', name: 'Malawi' },
    { code: 'MV', name: 'Maldives' },
    { code: 'ML', name: 'Mali' },
    { code: 'MT', name: 'Malte' },
    { code: 'MP', name: 'Mariannes du Nord, Œles' },
    { code: 'MA', name: 'Maroc' },
    { code: 'MH', name: 'Marshall, Œles' },
    { code: 'MQ', name: 'Martinique' },
    { code: 'MU', name: 'Maurice, Œle' },
    { code: 'MR', name: 'Mauritanie' },
    { code: 'YT', name: 'Mayotte' },
    { code: 'MX', name: 'Mexique' },
    { code: 'FM', name: 'Micronésie, Etats Fédérés de' },
    { code: 'MD', name: 'Moldova, République de' },
    { code: 'MC', name: 'Monaco' },
    { code: 'MN', name: 'Mongolie' },
    { code: 'MS', name: 'Montserrat' },
    { code: 'MZ', name: 'Mozambique' },
    { code: 'MM', name: 'Myanmar' },
    { code: 'NA', name: 'Namibie' },
    { code: 'NR', name: 'Nauru' },
    { code: 'NP', name: 'Népal' },
    { code: 'NI', name: 'Nicaragua' },
    { code: 'NE', name: 'Niger' },
    { code: 'NG', name: 'Nigéria' },
    { code: 'NU', name: 'Nioué' },
    { code: 'NF', name: 'Norfolk, Œle' },
    { code: 'NO', name: 'Norvège' },
    { code: 'NC', name: 'Nouvelle-Calédonie' },
    { code: 'NZ', name: 'Nouvelle-Zélande' },
    { code: 'IO', name: 'Océan indien,Territoire Britannique' },
    { code: 'UM', name: 'Œles mineures éloignées(Etats-Unis)' },
    { code: 'OM', name: 'Oman' },
    { code: 'UG', name: 'Ouganda' },
    { code: 'UZ', name: 'Ouzbékistan' },
    { code: 'PK', name: 'Pakistan' },
    { code: 'PW', name: 'Palaos' },
    { code: 'PS', name: 'Palestine, territoires ocode:upés' },
    { code: 'PA', name: 'Panama' },
    { code: 'PG', name: 'Papouasie Nouvelle Guinée' },
    { code: 'PY', name: 'Paraguay' },
    { code: 'NL', name: 'Pays-bas' },
    { code: 'PE', name: 'Pérou' },
    { code: 'PH', name: 'Philippines' },
    { code: 'PN', name: 'Pitcairn' },
    { code: 'PL', name: 'Pologne' },
    { code: 'PF', name: 'Polynésie française' },
    { code: 'PR', name: 'Porto Rico' },
    { code: 'PT', name: 'Portugal' },
    { code: 'QA', name: 'Qatar' },
    { code: 'RE', name: 'Réunion' },
    { code: 'RO', name: 'Roumanie' },
    { code: 'GB', name: 'Royaume-Uni' },
    { code: 'RU', name: 'Russie, Fédération de' },
    { code: 'RW', name: 'Rwanda' },
    { code: 'EH', name: 'Sahara ocode:idental' },
    { code: 'KN', name: 'Saint Kitts et Nevis' },
    { code: 'VC', name: 'Saint Vincent et les Grenadines' },
    { code: 'SH', name: 'Sainte-Hélène' },
    { code: 'LC', name: 'Sainte-Lucie' },
    { code: 'SM', name: 'Saint-Marin' },
    { code: 'PM', name: 'Saint-Pierre et Miquelon' },
    { code: 'SB', name: 'Salomon, Œles' },
    { code: 'WS', name: 'Samoa' },
    { code: 'AS', name: 'Samoa Américaines' },
    { code: 'ST', name: 'Sao Tomé-et-Principe' },
    { code: 'SN', name: 'Sénégal' },
    { code: 'SC', name: 'Seychelles' },
    { code: 'SL', name: 'Sierra Leone' },
    { code: 'SG', name: 'Singapour' },
    { code: 'SK', name: 'Slovaquie' },
    { code: 'SI', name: 'Slovénie' },
    { code: 'SO', name: 'Somalie' },
    { code: 'SD', name: 'Soudan' },
    { code: 'LK', name: 'Sri Lanka' },
    { code: 'SE', name: 'Suède' },
    { code: 'CH', name: 'Suisse' },
    { code: 'SR', name: 'Suriname' },
    { code: 'SJ', name: 'Svalbard et Œle Jan Mayen' },
    { code: 'SZ', name: 'Swaziland' },
    { code: 'SY', name: 'Syrienne, République arabe' },
    { code: 'TJ', name: 'Tadjikistan' },
    { code: 'TW', name: 'Taïwan, Province de Chine' },
    { code: 'TZ', name: 'Tanzanie' },
    { code: 'TD', name: 'Tchad' },
    { code: 'CZ', name: 'Tchèque, République' },
    { code: 'TF', name: 'Terres Australes Françaises' },
    { code: 'TH', name: 'Thaïlande' },
    { code: 'TP', name: 'Timor Oriental' },
    { code: 'TG', name: 'Togo' },
    { code: 'TK', name: 'Tokelau' },
    { code: 'TO', name: 'Tonga' },
    { code: 'TT', name: 'Trinitad et Tobago' },
    { code: 'TN', name: 'Tunisie' },
    { code: 'TM', name: 'Turkménistan' },
    { code: 'TC', name: 'Turks et Caïques, Œles' },
    { code: 'TR', name: 'Turquie' },
    { code: 'TV', name: 'Tuvalu' },
    { code: 'UA', name: 'Ukraine' },
    { code: 'UY', name: 'Uruguay' },
    { code: 'VU', name: 'Vanuatu' },
    { code: 'VA', name: 'Vatican (Saint-Siège)' },
    { code: 'VE', name: 'Venezuela' },
    { code: 'VN', name: 'Vietnam' },
    { code: 'WF', name: 'Wallis et Futuna' },
    { code: 'YE', name: 'Yémen' },
    { code: 'YU', name: 'Yougoslavie' },
    { code: 'ZM', name: 'Zambie' },
    { code: 'ZW', name: 'Zimbabwe' },

];
export const roles = [
  { name: 'ROLE_ADMIN', id: '1' },
  { name: 'ROLE_COMPTABLE', id: '21' },
  { name: 'ROLE_ETRANGER', id: '22' },
  { name: 'ROLE_AUTRE', id: '23' },
  { name: 'ROLE_MODIFICATION', id: '24' },

]
